In [3]:
import numpy as np
import pandas as pd

In [21]:
csv_list = []
for i in np.arange(0, 1):
    x = str(i).zfill(3)
    #csv_list = np.append(csv_list, pd.read_csv("updateModhopper_csv_files/Obvius_backlog_data_" + x + ".csv"))

['Meter name' '33 Gas' '34-CT-1 Makeup' ... nan nan nan]

In [22]:
pd.read_csv("updateModhopper_csv_files/Obvius_backlog_data_" + x + ".csv")

,Facility,Building 33,Building 34,Building 34.1,Building 50,Building 50.1,Building 50.2,Building 50.3,Building 50.4,Building 50.5,...,Building 66,Building 70,Building 70A,Building 71,Building 71.1,Building 71.2,Building 76,Building 88,Building 88.1,Building 88.2
0,Meter name,33 Gas,34-CT-1 Makeup,34-CT-2 Makeup,50 East Side Gas,50 West Side Gas,50A-CT-5 Makeup,50A-CT-6 Makeup,50B-CT-4 Makeup,50B-CT-4_5 Drain Flow,...,66 Gas,B70 Gas,B70A Gas,71 Gas,71-CT-4 Blowdown,71-CT-4 Makeup,76 Gas,88 Gas,88-CT-2 Blowdown,88-CT-2 Makeup
1,Meter id,lbnl_building33_gas_submeter_gas12700,lbnl_building34_water_submeter_34ct1makeup,lbnl_building34_water_submeter_34ct2makeup,lbnl_building50_gas_submeter_gas6900,lbnl_building50_gas_submeter_gas8030,lbnl_building50_water_submeter_50act5makeup,lbnl_building50_water_submeter_50act6makeup,lbnl_building50_water_submeter_50bct4makeup,lbnl_building50_water_submeter_50bctblowdown,...,lbnl_building66_gas_submeter_gas1300,lbnl_building70_gas_submeter_gas6700,lbnl_building70a_gas_submeter_gas6800,lbnl_building71_gas_submeter_gas1460,lbnl_building71_water_submeter_ctblowdown,lbnl_building71_water_submeter_ctmakeup,lbnl_building76_gas_submeter_gas2150,lbnl_building88_gas_submeter_8100gas,lbnl_building88_water_submeter_88ct2blowdown,lbnl_building88_water_submeter_88ct2makeup
2,Timestamp,Building 33 - 33 Gas (raw),Building 34 - 34-CT-1 Makeup (raw),Building 34 - 34-CT-2 Makeup (raw),Building 50 - 50 East Side Gas (raw),Building 50 - 50 West Side Gas (raw),Building 50 - 50A-CT-5 Makeup (raw),Building 50 - 50A-CT-6 Makeup (raw),Building 50 - 50B-CT-4 Makeup (raw),Building 50 - 50B-CT-4_5 Drain Flow (raw),...,Building 66 - 66 Gas (raw),Building 70 - B70 Gas (raw),Building 70A - B70A Gas (raw),Building 71 - 71 Gas (raw),Building 71 - 71-CT-4 Blowdown (raw),Building 71 - 71-CT-4 Makeup (raw),Building 76 - 76 Gas (raw),Building 88 - 88 Gas (raw),Building 88 - 88-CT-2 Blowdown (raw),Building 88 - 88-CT-2 Makeup (raw)
3,2015-03-19 13:25,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-03-19 13:30,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2015-03-19 13:35,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2015-03-19 13:40,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2015-03-19 13:45,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2015-03-19 13:50,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2015-03-19 13:55,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2015-03-19 14:00,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2015-03-19 14:05,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2015-03-19 14:10,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2015-03-19 14:15,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2015-03-19 14:20,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2015-03-19 14:25,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2015-03-19 14:30,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2015-03-19 14:35,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2015-03-19 14:40,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2015-03-19 14:45,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2015-03-19 14:50,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2015-03-19 14:55,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2015-03-19 15:00,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2015-03-19 15:05,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2015-03-19 15:10,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2015-03-19 15:15,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2015-03-19 15:20,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2015-03-19 15:25,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2015-03-19 15:30,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2015-03-19 15:35,NaN,NaN,NaN,NaN,NaN,90.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49973,2015-09-13 13:10,NaN,NaN,NaN,NaN,NaN,83454,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316790,NaN,NaN,NaN,NaN
49974,2015-09-13 13:15,NaN,NaN,NaN,NaN,NaN,83460,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316800,NaN,NaN,NaN,NaN
49975,2015-09-13 13:20,NaN,NaN,NaN,NaN,NaN,83467,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316810,NaN,NaN,NaN,NaN
49976,2015-09-13 13:25,NaN,NaN,NaN,NaN,NaN,83473,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316820,NaN,NaN,NaN,NaN
49977,2015-09-13 13:30,NaN,NaN,NaN,NaN,NaN,83479,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316820,NaN,NaN,NaN,NaN
49978,2015-09-13 13:35,NaN,NaN,NaN,NaN,NaN,83485,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316830,NaN,NaN,NaN,NaN
49979,2015-09-13 13:40,NaN,NaN,NaN,NaN,NaN,83491,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316840,NaN,NaN,NaN,NaN
49980,2015-09-13 13:45,NaN,NaN,NaN,NaN,NaN,83497,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316850,NaN,NaN,NaN,NaN
49981,2015-09-13 13:50,NaN,NaN,NaN,NaN,NaN,83503,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316850,NaN,NaN,NaN,NaN
49982,2015-09-13 13:55,NaN,NaN,NaN,NaN,NaN,83509,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316860,NaN,NaN,NaN,NaN
49983,2015-09-13 14:00,NaN,NaN,NaN,NaN,NaN,83514,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316870,NaN,NaN,NaN,NaN
49984,2015-09-13 14:05,NaN,NaN,NaN,NaN,NaN,83520,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316880,NaN,NaN,NaN,NaN
49985,2015-09-13 14:10,NaN,NaN,NaN,NaN,NaN,83526,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316890,NaN,NaN,NaN,NaN
49986,2015-09-13 14:15,NaN,NaN,NaN,NaN,NaN,83531,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316890,NaN,NaN,NaN,NaN
49987,2015-09-13 14:20,NaN,NaN,NaN,NaN,NaN,83537,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316900,NaN,NaN,NaN,NaN
49988,2015-09-13 14:25,NaN,NaN,NaN,NaN,NaN,83543,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316910,NaN,NaN,NaN,NaN
49989,2015-09-13 14:30,NaN,NaN,NaN,NaN,NaN,83548,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316920,NaN,NaN,NaN,NaN
49990,2015-09-13 14:35,NaN,NaN,NaN,NaN,NaN,83554,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316930,NaN,NaN,NaN,NaN
49991,2015-09-13 14:40,NaN,NaN,NaN,NaN,NaN,83560,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316930,NaN,NaN,NaN,NaN
49992,2015-09-13 14:45,NaN,NaN,NaN,NaN,NaN,83565,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316940,NaN,NaN,NaN,NaN
49993,2015-09-13 14:50,NaN,NaN,NaN,NaN,NaN,83571,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316950,NaN,NaN,NaN,NaN
49994,2015-09-13 14:55,NaN,NaN,NaN,NaN,NaN,83577,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316960,NaN,NaN,NaN,NaN
49995,2015-09-13 15:00,NaN,NaN,NaN,NaN,NaN,83582,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316970,NaN,NaN,NaN,NaN
49996,2015-09-13 15:05,NaN,NaN,NaN,NaN,NaN,83588,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316980,NaN,NaN,NaN,NaN
49997,2015-09-13 15:10,NaN,NaN,NaN,NaN,NaN,83594,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316980,NaN,NaN,NaN,NaN
49998,2015-09-13 15:15,NaN,NaN,NaN,NaN,NaN,83600,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,316990,NaN,NaN,NaN,NaN
49999,2015-09-13 15:20,NaN,NaN,NaN,NaN,NaN,83606,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,317000,NaN,NaN,NaN,NaN
50000,2015-09-13 15:29,NaN,NaN,NaN,NaN,NaN,83616,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,317020,NaN,NaN,NaN,NaN
50001,2015-09-13 15:35,NaN,NaN,NaN,NaN,NaN,83623,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,317030,NaN,NaN,NaN,NaN
50002,2015-09-13 15:40,NaN,NaN,NaN,NaN,NaN,83628,85297,13040,220,...,NaN,NaN,NaN,NaN,9980,317030,NaN,NaN,NaN,NaN

In [ ]:
#https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html